# Generated by Django 5.0.1 on 2024-02-01 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_reg',
            old_name='address',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user_reg',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user_reg',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
