# Generated by Django 5.0.1 on 2024-02-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_address_user_reg_name_remove_user_reg_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='age',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
