# Generated by Django 5.0.1 on 2024-02-01 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_age_user_reg_address_remove_user_reg_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_reg',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
