# Generated by Django 5.0.1 on 2024-02-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='lname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
