# Generated by Django 5.0.1 on 2024-02-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_skilled_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtype', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
