# Generated by Django 4.2.5 on 2024-02-26 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='skilled_worker_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtype', models.CharField(max_length=50, null=True)),
                ('experience', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('sworker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.skilled_worker')),
            ],
        ),
    ]
