# Generated by Django 4.2.5 on 2024-02-26 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_skilled_worker_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('sworker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.skilled_worker_details')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user_reg')),
            ],
        ),
    ]
