# Generated by Django 4.2.5 on 2024-02-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
