# Generated by Django 4.2.5 on 2024-02-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
