# Generated by Django 4.2.5 on 2024-02-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
