# Generated by Django 4.2.5 on 2024-02-27 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_interview_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.jobapplication'),
        ),
    ]
