# Generated by Django 4.2.5 on 2024-02-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_interview_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(max_length=200, null=True)),
                ('video', models.FileField(null=True, upload_to='')),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
