# Generated by Django 4.2.5 on 2024-02-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_service_feedback_ss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
