# Generated by Django 4.2.5 on 2024-02-27 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, null=True)),
                ('feedback', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('action', models.CharField(max_length=50, null=True)),
                ('ss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_reg')),
            ],
        ),
    ]
